// Generated by CoffeeScript 1.12.4
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  App.SensusView = (function(superClass) {
    extend(SensusView, superClass);

    function SensusView() {
      return SensusView.__super__.constructor.apply(this, arguments);
    }

    SensusView.prototype.scriptLocation = AppSupport.scriptLocation();

    SensusView.prototype.replaceRootElement = true;

    return SensusView;

  })(AppSupport.SelfLoadingView);

}).call(this);
