// Generated by CoffeeScript 1.12.4
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Sensus.ProposalCell = (function(superClass) {
    extend(ProposalCell, superClass);

    function ProposalCell() {
      this.render = bind(this.render, this);
      return ProposalCell.__super__.constructor.apply(this, arguments);
    }

    ProposalCell.prototype.scriptLocation = AppSupport.scriptLocation();

    ProposalCell.prototype.render = function() {
      ProposalCell.__super__.render.apply(this, arguments);
      this.$('#ProposalNumber').html(this.model.get('issue_number'));
      this.$('#ProposalTitle').html(this.model.get('title'));
      return this.$el;
    };

    return ProposalCell;

  })(AppSupport.SelfLoadingView);

}).call(this);
