// Generated by CoffeeScript 1.12.4
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Sensus.SensusApp = (function(superClass) {
    extend(SensusApp, superClass);

    function SensusApp() {
      this.render = bind(this.render, this);
      this.initialize = bind(this.initialize, this);
      return SensusApp.__super__.constructor.apply(this, arguments);
    }

    SensusApp.prototype.navBar = null;

    SensusApp.prototype.mainContent = null;

    SensusApp.prototype.scriptLocation = AppSupport.scriptLocation();

    SensusApp.prototype.initialize = function(options) {
      SensusApp.__super__.initialize.call(this, options);
      this.navBar = new Sensus.NavBar;
      return this.mainContent = new Sensus.MainContent;
    };

    SensusApp.prototype.render = function() {
      this.$el.empty();
      this.$el.append(this.navBar.render());
      this.$el.append(this.mainContent.render());
      return this.$el;
    };

    return SensusApp;

  })(AppSupport.SelfLoadingView);

}).call(this);
