// Generated by CoffeeScript 1.12.4
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Sensus.Proposal = (function(superClass) {
    extend(Proposal, superClass);

    function Proposal() {
      return Proposal.__super__.constructor.apply(this, arguments);
    }

    return Proposal;

  })(Backbone.Model);

  Sensus.Proposals = (function(superClass) {
    extend(Proposals, superClass);

    function Proposals() {
      return Proposals.__super__.constructor.apply(this, arguments);
    }

    Proposals.prototype.model = Sensus.Proposal;

    Proposals.prototype.comparator = 'id';

    Proposals.prototype.url = '/testdata/Proposals.json';

    return Proposals;

  })(Backbone.Collection);

}).call(this);
